Adicinado mais informações no README
JulianoGTZ/receitas pull request #14
Opened 2020-07-06 17:21 UTC by JoaoCarlosAzevedo

#6

2020-07-06 17:26 UTC, JulianoGTZ requested changes

2020-07-06 17:26 UTC, JulianoGTZ commented on README.md
> +| Cozinheiros   |
o que você acha de nessa lista dos cozinheiros colocar o link do github de cada um?

2020-07-06 17:29 UTC, JoaoCarlosAzevedo commented on README.md
> +| Cozinheiros   |
Excelente ideia! Vou organizar

2020-07-06 17:48 UTC, JulianoGTZ commented on README.md
> +| Cozinheiros   |
**Sugestão**

[![](https://avatars1.githubusercontent.com/u/19213771?&v=4&s=80)](https://github.com/JoaoCarlosAzevedo) 
-|
[@JoaoCarlosAzevedo ](https://github.com/joaocarlosazevedo)

2020-07-06 17:49 UTC, JulianoGTZ commented on README.md
> +| Cozinheiros   |
Copiei dessa [Readme Descolado aqui](https://github.com/sweetalert2/sweetalert2/blob/master/README.md)

2020-07-06 17:51 UTC, JoaoCarlosAzevedo commented on README.md
> +| Cozinheiros   |
Ok, vou fazer mais tarde.

2020-07-07 11:56 UTC, JulianoGTZ commented
👏 👏 👏 👏  LGTM

2020-07-07 11:56 UTC, JulianoGTZ approved these changes

2020-07-07 11:56 UTC, merged